include:
  - board: zitaotech_q10
    shield: zitaotech_q10
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  
  
  
  
  - board: sofle_dongle
    shield: st7789_display
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  - board: sofle_dongle_left
    shield: lpm_view;left_bbtrackball_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
  - board: sofle_dongle_right
    shield: lpm_view;right_trackpoint_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
